# اطلاعات کلی سایت
site_name: 'WebKesht: The Smart Irrigation System'
site_url: https://webkesht.com/
site_description: 'WebKesht Documentation'
site_author: 'The WebKesht Team'

# مسیر خروجی
site_dir: site/fa

# تنظیمات پوسته
theme:
  name: material
  language: en
  custom_dir: overrides
  palette:
    - scheme: default
      primary: green
      accent: light green
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  
  font:
    text: Vazirmatn
    code: 'Fira Code'
  
palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  
icon:
    logo: material/leaf
  
favicon:  images/favicon.ico

# CSS سفارشی
extra_css:
  - stylesheets/custom.css
  - stylesheets/MyStyle.css
  - stylesheets/Article.css

extra_javascript:
- javascripts/custom.js



# تنظیمات اضافی
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/webkesht
    - icon: fontawesome/brands/instagram  
      link: https://instagram.com/webkesht
    - icon: fontawesome/solid/envelope
      link: mailto:support@webkesht.com

# پلاگین‌ها (ساده شده)
plugins:
  - search:
      separator: '[\s\-\.]+'
  - blog:
      blog_dir: blog
  - meta:
      meta_file: .meta.yml

# افزونه‌های مارک‌داون ضروری
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
 
 
# ساختار ناوبری
nav:
  - Home: index.md
  - quick-start:
    - Comprehensive System Guide : quick-start/Guide.md
  - User Guides:
    - user-guide/index.md
    - Comprehensive Soil Texture Guide: user-guide/Soil.md
    - Comprehensive Vegetation Cover Guide: user-guide/Vegetation.md
    - Comprehensive Irrigation System Guide: user-guide/Irrigation.md
  - blog:
    - blog/index.md
  - Login / Sign Up:
    - http://app.webkesht.com
  - Support:
    - support/index.md
